// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystem.Data.Data;

#nullable disable

namespace SchoolManagementSystem.Data.Migrations
{
    [DbContext(typeof(SchoolManagementSystemDbContext))]
    [Migration("20260122175615_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Common.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Common.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Common.StaffRoleAssignment", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("StaffId", "Role");

                    b.ToTable("StaffRoleAssignments");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Common.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grade")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int?>("LeadTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("LeadTeacherId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.ParentStudent", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ParentId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ParentStudents");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.StudentClass", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("StudentClasses");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Common.Attendance", b =>
                {
                    b.HasOne("SchoolManagementSystem.Data.Data.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Common.Grade", b =>
                {
                    b.HasOne("SchoolManagementSystem.Data.Data.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Data.Data.Common.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Common.StaffRoleAssignment", b =>
                {
                    b.HasOne("SchoolManagementSystem.Data.Data.Models.Staff", "Staff")
                        .WithMany("Roles")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Common.Subject", b =>
                {
                    b.HasOne("SchoolManagementSystem.Data.Data.Models.Staff", null)
                        .WithMany("Subjects")
                        .HasForeignKey("StaffId");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Class", b =>
                {
                    b.HasOne("SchoolManagementSystem.Data.Data.Models.Staff", "LeadTeacher")
                        .WithMany()
                        .HasForeignKey("LeadTeacherId");

                    b.HasOne("SchoolManagementSystem.Data.Data.Models.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeadTeacher");

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Parent", b =>
                {
                    b.OwnsOne("SchoolManagementSystem.Data.Data.Common.Info", "Info", b1 =>
                        {
                            b1.Property<int>("ParentId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.HasKey("ParentId");

                            b1.ToTable("Parents");

                            b1.WithOwner()
                                .HasForeignKey("ParentId");

                            b1.OwnsMany("SchoolManagementSystem.Data.Data.Common.EmailAddress", "Emails", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Email")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("nvarchar(150)");

                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OwnerId");

                                    b2.ToTable("Parents_Emails");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.OwnsMany("SchoolManagementSystem.Data.Data.Common.PhoneNumber", "PhoneNumbers", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)");

                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OwnerId");

                                    b2.ToTable("Parents_PhoneNumbers");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.Navigation("Emails");

                            b1.Navigation("PhoneNumbers");
                        });

                    b.Navigation("Info")
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.ParentStudent", b =>
                {
                    b.HasOne("SchoolManagementSystem.Data.Data.Models.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Data.Data.Models.Student", "Student")
                        .WithMany("Parents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Staff", b =>
                {
                    b.HasOne("SchoolManagementSystem.Data.Data.Models.School", null)
                        .WithMany("Staff")
                        .HasForeignKey("SchoolId");

                    b.OwnsOne("SchoolManagementSystem.Data.Data.Common.Info", "Info", b1 =>
                        {
                            b1.Property<int>("StaffId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.HasKey("StaffId");

                            b1.ToTable("Staff");

                            b1.WithOwner()
                                .HasForeignKey("StaffId");

                            b1.OwnsMany("SchoolManagementSystem.Data.Data.Common.EmailAddress", "Emails", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Email")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("nvarchar(150)");

                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OwnerId");

                                    b2.ToTable("Staff_Emails");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.OwnsMany("SchoolManagementSystem.Data.Data.Common.PhoneNumber", "PhoneNumbers", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)");

                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OwnerId");

                                    b2.ToTable("Staff_PhoneNumbers");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.Navigation("Emails");

                            b1.Navigation("PhoneNumbers");
                        });

                    b.Navigation("Info")
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Student", b =>
                {
                    b.HasOne("SchoolManagementSystem.Data.Data.Models.School", null)
                        .WithMany("Students")
                        .HasForeignKey("SchoolId");

                    b.OwnsOne("SchoolManagementSystem.Data.Data.Common.Info", "Info", b1 =>
                        {
                            b1.Property<int>("StudentId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.HasKey("StudentId");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");

                            b1.OwnsMany("SchoolManagementSystem.Data.Data.Common.EmailAddress", "Emails", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Email")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("nvarchar(150)");

                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OwnerId");

                                    b2.ToTable("Students_Emails");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.OwnsMany("SchoolManagementSystem.Data.Data.Common.PhoneNumber", "PhoneNumbers", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)");

                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OwnerId");

                                    b2.ToTable("Students_PhoneNumbers");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.Navigation("Emails");

                            b1.Navigation("PhoneNumbers");
                        });

                    b.Navigation("Info")
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.StudentClass", b =>
                {
                    b.HasOne("SchoolManagementSystem.Data.Data.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Data.Data.Models.Student", "Student")
                        .WithMany("Classes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.School", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Staff");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Staff", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SchoolManagementSystem.Data.Data.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Classes");

                    b.Navigation("Grades");

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
